[build]
command = "npm run build:both"
publish = "dist"

[functions]
directory = "netlify/functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[headers]]
  for = "/rbg-designer.iife.js.map"
  [headers.values]
    cache-control = "no-cache, no-store, must-revalidate"
    pragma = "no-cache"
    expires = "0"