[build]
command = "npm run build:both"
publish = "dist"

[functions]
directory = "netlify/functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[headers]]
  for = "/rbg-designer.iife.js.map"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
    cache-control = "no-cache, no-store, must-revalidate"
    pragma = "no-cache"
    expires = "0"

[[headers]]
  for = "/rbg-designer.iife.js"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
    cache-control = "no-cache, no-store, must-revalidate"
    pragma = "no-cache"
    expires = "0"